CREATE UNIQUE INDEX IF NOT EXISTS news_posts_slug_key ON public.news_posts (slug);
CREATE UNIQUE INDEX IF NOT EXISTS show_posts_slug_key ON public.show_posts (slug);

INSERT INTO public.news_posts (slug, title, category, excerpt, body, author, published) VALUES
('kajiado-water-project-launch','Kajiado Town water project brings taps closer to 4,000 homes','County News','A new borehole and distribution line commissioned this week is expected to cut daily water queues in three estates.','Residents of Kajiado Town will spend less time queueing for water after the county commissioned a new borehole and distribution line serving three estates.\n\nSpeaking at the launch, county officials said the project adds capacity for roughly 4,000 households and will be run with a community water committee that reports monthly on meter readings and revenue.\n\nBus Radio 99.9FM listeners raised water rationing as their top concern in our morning phone-ins for three consecutive weeks. The station will keep following the project and publish the committee''s first report on air.','Bus Radio Newsroom',true),
('youth-newsroom-training','Twenty young reporters trained in the Bus Radio community newsroom','Youth','A two-week practical course covered interviewing, phone recording, fact-checking and safety for community correspondents.','Twenty young people from Kajiado Central and Kajiado East completed a two-week community reporting course hosted at the Bus Radio 99.9FM studio.\n\nThe course covered interviewing, recording clean audio on a phone, verifying claims before broadcast, and staying safe while reporting on sensitive local issues.\n\nGraduates will feed weekly ward updates into the county bulletin, and the best submissions will air on Habari za Kaunti. Listeners can send tips and recordings through the Report page on this website.','Bus Radio Newsroom',true),
('maa-language-preservation','Maa language programming expands to weekend afternoons','Culture','Elders and young speakers share proverbs, oral history and music in an expanded Maa-language slot.','Bus Radio 99.9FM is expanding Maa-language programming to weekend afternoons following steady listener demand.\n\nThe slot pairs elders with young speakers to discuss proverbs, oral history, naming traditions and pastoralist knowledge, mixed with Maa music from across the county.\n\nSchools in Kajiado Town have asked for recordings to use in class, and the station is preparing a short archive of the best segments.','Bus Radio Newsroom',true),
('county-health-outreach','Free health outreach reaches Kajiado wards after on-air campaign','Health','Screening for blood pressure, diabetes and maternal health ran across five wards for a week.','A week-long free health outreach covering blood pressure, diabetes screening and maternal health services ran across five Kajiado wards.\n\nHealth workers said turnout was strongest where the schedule was announced on radio the previous evening, with several hundred people screened each day.\n\nBus Radio 99.9FM carried daily announcements and hosted a live question session with clinical officers who answered listener calls on medication and follow-up visits.','Bus Radio Newsroom',true),
('ward-accountability-forum','Ward accountability forum broadcast live from Kajiado Town','Governance','Residents put development questions directly to ward representatives in an open, on-air forum.','Residents put questions on roads, bursaries and water projects directly to their ward representatives during an open forum broadcast live on Bus Radio 99.9FM.\n\nThe two-hour session mixed floor questions with calls and messages from listeners across the county, with the station keeping a public list of the commitments made.\n\nFollow-up editions will check progress on each commitment. Send your ward''s issues through the Report page and they will be raised in the next forum.','Bus Radio Newsroom',true),
('livestock-market-prices','Livestock market prices steady as rains improve pasture','Community','Traders at Kajiado''s main market report firmer prices as pasture recovers after good rains.','Traders at Kajiado''s main livestock market report steadier prices as pasture recovers following good rains across the county.\n\nBuyers from Nairobi returned in larger numbers, and market officials say volumes are close to the levels seen before the last dry spell.\n\nBus Radio 99.9FM carries market updates in the midday bulletin so pastoralists can plan sales before travelling.','Bus Radio Newsroom',true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.show_posts (slug, name, category, host, days, time_slot, language, description, published) VALUES
('habari-za-kaunti','Habari za Kaunti','News','Bus Radio Newsroom','Daily','7:00 AM, 1:00 PM, 7:00 PM','Kiswahili / Maa','County bulletins three times a day — verified, local and bilingual news from across Kajiado.',true),
('jukwaa-la-kazi','Jukwaa La Kazi','Talk Shows','MC Jumah','Monday to Friday','9:00 AM - 12:00 PM','Kiswahili','Jobs, hustles and enterprise — practical conversations about work, skills and opportunity in Kajiado.',true),
('jukwaa-la-siasa','Jukwaa La Siasa','Talk Shows','Milanoi Antonia','Wednesday','8:00 PM - 10:00 PM','Kiswahili','Open political debate with leaders and residents, focused on county development and accountability.',true),
('qwetu-afrika','Qwetu Afrika','Music','DJ Kitts','Friday & Saturday','8:00 PM - 11:00 PM','Kiswahili / English','The best of African music — afrobeats, bongo, benga and Maasai sounds to close the week.',true),
('faraja-show','Faraja Show','Religious','Kaka J','Sunday','6:00 AM - 9:00 AM','Kiswahili','Gospel music, scripture and encouragement to start the week with hope.',true),
('mahojiano-live','Mahojiano Live','Talk Shows','Bus Radio','Tuesday & Thursday','10:00 AM - 12:00 PM','Kiswahili','Long-form studio interviews with leaders, entrepreneurs and community voices.',true),
('sauti-ya-mwanamke','Sauti ya Mwanamke','Gender & Community','Bus Radio','Thursday','2:00 PM - 4:00 PM','Kiswahili / Maa','Women''s health, rights, business and family life, with expert guests and listener calls.',true),
('vijana-tunaweza','Vijana Tunaweza','Youth','Bus Radio','Saturday','4:00 PM - 6:00 PM','Kiswahili / English','Youth talent, education, sport and mental health — driven by young people in Kajiado.',true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.live_links (title, platform, url, description, is_live, published)
SELECT 'Bus Radio 99.9FM on YouTube','YouTube','https://www.youtube.com/@busradio99.9fm','Watch studio sessions, interviews and event coverage on our YouTube channel.',false,true
WHERE NOT EXISTS (SELECT 1 FROM public.live_links WHERE url = 'https://www.youtube.com/@busradio99.9fm');